[package]
name = "oscar/example-data-solution"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Sift = "csqrl/sift@0.0.9"
T = "osyrisrblx/t@3.1.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.2"
